### ISSUE TITLE
./build_userland.sh fild

### ISSUE THREAD

**Issue by Neo110** [JoakimSoderberg/catcierge#18]
i runing ./build_userland.sh  

print this

~/下载/cimage/catcierge/rpi_userland ~/下载/cimage/catcierge
~/下载/cimage/catcierge/rpi_userland/build/arm-linux/release ~/下载/cimage/catcierge/rpi_userland ~/下载/cimage/catcierge
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/arm-linux-gnueabihf-gcc" is not able to compile a
  simple test program.

  It fails with the following output:

   Change Dir: /home/chusen/下载/cimage/catcierge/rpi_userland/build/arm-linux/release/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_65df9/fast"

  /usr/bin/make -f CMakeFiles/cmTC_65df9.dir/build.make
  CMakeFiles/cmTC_65df9.dir/build

  make[1]: Entering directory
  '/home/chusen/下载/cimage/catcierge/rpi_userland/build/arm-linux/release/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_65df9.dir/testCCompiler.c.o

  /usr/bin/arm-linux-gnueabihf-gcc -U_FORTIFY_SOURCE -mcpu=arm1176jzf-s
  -mfpu=vfp -mfloat-abi=hard -o CMakeFiles/cmTC_65df9.dir/testCCompiler.c.o
  -c
  /home/chusen/下载/cimage/catcierge/rpi_userland/build/arm-linux/release/CMakeFiles/CMakeTmp/testCCompiler.c

  
  /home/chusen/下载/cimage/catcierge/rpi_userland/build/arm-linux/release/CMakeFiles/CMakeTmp/testCCompiler.c:
  In function ‘main’:

  
  /home/chusen/下载/cimage/catcierge/rpi_userland/build/arm-linux/release/CMakeFiles/CMakeTmp/testCCompiler.c:11:1:
  sorry, unimplemented: Thumb-1 hard-float VFP ABI

   { (void)argv; return argc-1;}
   ^

  CMakeFiles/cmTC_65df9.dir/build.make:65: recipe for target
  'CMakeFiles/cmTC_65df9.dir/testCCompiler.c.o' failed

  make[1]: *** [CMakeFiles/cmTC_65df9.dir/testCCompiler.c.o] Error 1

  make[1]: Leaving directory
  '/home/chusen/下载/cimage/catcierge/rpi_userland/build/arm-linux/release/CMakeFiles/CMakeTmp'

  Makefile:126: recipe for target 'cmTC_65df9/fast' failed

  make: *** [cmTC_65df9/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!
See also "/home/chusen/下载/cimage/catcierge/rpi_userland/build/arm-linux/release/CMakeFiles/CMakeOutput.log".
See also "/home/chusen/下载/cimage/catcierge/rpi_userland/build/arm-linux/release/CMakeFiles/CMakeError.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
~/下载/cimage/catcierge/rpi_userland ~/下载/cimage/catcierge
~/下载/cimage/catcierge

**Comment by JoakimSoderberg** [comment]
ok but please keep this in one ticket at #17
