### ISSUE TITLE
Under testing phase - images are missing

### ISSUE THREAD

**Issue by patmoore** [JoakimSoderberg/catcierge#4]
match_fail__fail01.png ( for example ) 

The images that showed the first failure are missing.

**Comment by JoakimSoderberg** [comment]
Hello @patmoore you'll need to provide a bit more context to that statement. What are you trying to run exactly?

**Comment by JoakimSoderberg** [comment]
I guess you're trying to run the tests. And simply followed the Linux/OSX instructions? I see now that I forgot to mention that you need to clone the submodules for stuff to work. So most likely whatever issue you're having should be solved by:

```
git submodule update --init
```

Just out of curiousity, where did you find this project? All of a sudden it's getting a bunch of stars :)
Oh and are you planning to build a cat door?

**Comment by JoakimSoderberg** [comment]
Ok found it on hacker news... :)

**Comment by patmoore** [comment]
Yeap :-) hacker news ....

Viewing the project via: https://joakimsoderberg.github.io/catcierge/

![screen shot 2015-10-08 at 11 20 50 am](https://cloud.githubusercontent.com/assets/63212/10375657/ac5fa014-6dae-11e5-9d19-11472ac11527.png)

**Comment by JoakimSoderberg** [comment]
Fixed, thanks
